### ISSUE TITLE
Pb with running busco with AnnotationPreprocessing and Singularity

### ISSUE THREAD

**Issue by LucileSol** [NBISweden/pipelines-nextflow#28]
I tried to run the pipeline AnnotationPreprocessing with Singularity like this :

```
nextflow run -c params.config -profile nbis,singularity ~/git/NBIS/pipelines-nextflow/AnnotationPreprocessing/AnnotationPreprocessing.nf
```
my params.config :

```
// Workflow parameters
params.genome = 'cns_p_ctg_mod_lr_pilon_x3_mtmask.fasta'
params.outdir = 'results'
params.min_length = 1000
// Use `busco --list-datasets` for full list of available lineage sets
params.busco_lineage = [ 'arachnida_odb10', 'bacteria_odb10' ]
```

My busco folders are created and empty

and in .command.log I get : 

```
nxf-scratch-dir node-a02:/scratch/nxf.ggWYtc0RKT
ESC[33mWARNING:ESC[0m Skipping mount /sw/easybuild/software/Singularity/3.5.2/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
INFO:   ***** Start a BUSCO v4.0.2 analysis, current time: 05/13/2020 11:37:07 *****
INFO:   Configuring BUSCO with /usr/local/config/config.ini
INFO:   Mode is genome
INFO:   Input file is cns_p_ctg_mod_lr_pilon_x3_mtmask_purified.fa
INFO:   Downloading information on latest versions of BUSCO data...
CRITICAL:       Unhandled exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/busco/run_BUSCO.py", line 167, in run_BUSCO
    config_manager.load_busco_config(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/busco/BuscoLogger.py", line 55, in wrapped_func
    self.retval = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/busco/ConfigManager.py", line 46, in load_busco_config
    self.config.validate()
  File "/usr/local/lib/python3.7/site-packages/busco/BuscoConfig.py", line 243, in validate
    self._init_downloader()
  File "/usr/local/lib/python3.7/site-packages/busco/BuscoConfig.py", line 49, in _init_downloader
    self.downloader = BuscoDownloadManager(self)
  File "/usr/local/lib/python3.7/site-packages/busco/BuscoDownloadManager.py", line 49, in __init__
    self._load_versions()
  File "/usr/local/lib/python3.7/site-packages/busco/BuscoDownloadManager.py", line 58, in _load_versions
    with open(versions_file, "r") as v_file:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/nxf.ggWYtc0RKT/busco_downloads/file_versions.tsv'
```

**Comment by mahesh-panchal** [comment]
[Update] Grr, this one has lots of issues. 

- Biocontainers container doesn't mount `/etc/resolv.conf` correctly (did the usual fix).
- AUGUSTUS_CONFIG_PATH is not set when using the container, and that needs to be writable (fixed by copying to tmp dir and exporting).
- Next issue is a missing library in the container (- Need to fix bioconda recipe - will create a new container for now).
```
ldd /usr/local/bin/tblastn
	/lib64/ld-linux-x86-64.so.2 (0x7f177c7f0000)
	libz.so.1 => /usr/local/bin/../lib/libz.so.1 (0x7f177ca40000)
Error loading shared library libbz2.so.1: No such file or directory (needed by /usr/local/bin/tblastn)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f177c7f0000)
	libnsl.so.1 => /lib/libnsl.so.1 (0x7f177c5d8000)
	librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7f177c7f0000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f177c7f0000)
	libstdc++.so.6 => /usr/local/bin/../lib/libstdc++.so.6 (0x7f177c8cc000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f177c7f0000)
	libgomp.so.1 => /usr/local/bin/../lib/libgomp.so.1 (0x7f177c89f000)
	libgcc_s.so.1 => /usr/local/bin/../lib/libgcc_s.so.1 (0x7f177c88b000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f177c7f0000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7f177c3b6000)
```

**Comment by mahesh-panchal** [comment]
Testing the Busco developers own images before writing my own ..
