### ISSUE TITLE
error TranscriptAssembly.nf with fastp

### ISSUE THREAD

**Issue by LucileSol** [NBISweden/pipelines-nextflow#60]
I am running the following command :
 nextflow run -c params_scriptseq.config -profile nbis,singularity ~/git/NBIS/pipelines-nextflow/TranscriptAssembly/TranscriptAssembly.nf

param file : 
// Workflow parameters
params.reads = 'Gb*_{R1,R2}.fastq.gz'
params.genome = 'genome.fa'
params.single_end = false
params.outdir = 'results_scriptseq_Gb'
params.skip_trimming = false
params.trimmer = 'fastp'
params.fastp_options = ' -Q -L'
params.trimmomatic_adapter_path = '/projects/references/adapters/TruSeq3_all.fa'
params.trimmomatic_clip_options = 'LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36'
params.hisat2_options = ' --fr'
params.stringtie_options = ' --fr'
params.multiqc_config = "/home/lucso605/git/NBIS/pipelines-nextflow/TranscriptAssembly/config/multiqc_conf.yml"

and get the following error

Error executing process > 'transcript_assembly:fastp (Gb_ROV6_3)'

Caused by:
  Process `transcript_assembly:fastp (Gb_ROV6_3)` terminated with an error exit status (127)

Command executed:

  fastp  -Q -L -w 2 -i Gb_ROV6_3_R1.fastq.gz -I Gb_ROV6_3_R2.fastq.gz \
      -o Gb_ROV6_3_fastp-trimmed_R1.fastq.gz \
      -O Gb_ROV6_3_fastp-trimmed_R2.fastq.gz \
      --json Gb_ROV6_3_fastp.json

Command exit status:
  127

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /sw/easybuild/software/Singularity/3.8.0/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  /bin/bash: line 0: cd: /scratch/nxf.XCNzlbfCs9: No such file or directory
  /bin/bash: .command.run: No such file or directory

Work dir:
  /projects/annotation/species/RNAseq/work/e2/abcd73a4279e144994b22926615f69

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by mahesh-panchal** [comment]
This is confusing. Nextflow isn't able to find the scratch directory it created.

**Comment by LucileSol** [comment]
If I use conda instead of singularity

Error executing process > 'transcript_assembly:multiqc'

Caused by:
  Process `transcript_assembly:multiqc` terminated with an error exit status (1)

Command executed:

  multiqc . -c multiqc_conf.yml

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/projects/annotation/geodia_baretti/RNAseq/work/conda/multiqc-c98eb6b85dda6e7c6d0116ad2fc6861c/bin/multiqc", line 6, in <module>
      from multiqc.__main__ import multiqc
    File "/projects/annotation/geodia_baretti/RNAseq/work/conda/multiqc-c98eb6b85dda6e7c6d0116ad2fc6861c/lib/python3.9/site-packages/multiqc/__init__.py", line 16, in <module>
      from .multiqc import run
    File "/projects/annotation/geodia_baretti/RNAseq/work/conda/multiqc-c98eb6b85dda6e7c6d0116ad2fc6861c/lib/python3.9/site-packages/multiqc/multiqc.py", line 37, in <module>
      from .plots import table
    File "/projects/annotation/geodia_baretti/RNAseq/work/conda/multiqc-c98eb6b85dda6e7c6d0116ad2fc6861c/lib/python3.9/site-packages/multiqc/plots/table.py", line 9, in <module>
      from multiqc.utils import config, report, util_functions, mqc_colour
    File "/projects/annotation/geodia_baretti/RNAseq/work/conda/multiqc-c98eb6b85dda6e7c6d0116ad2fc6861c/lib/python3.9/site-packages/multiqc/utils/mqc_colour.py", line 7, in <module>
      import spectra
    File "/projects/annotation/geodia_baretti/RNAseq/work/conda/multiqc-c98eb6b85dda6e7c6d0116ad2fc6861c/lib/python3.9/site-packages/spectra/__init__.py", line 1, in <module>
      from .core import COLOR_SPACES, Color, Scale
    File "/projects/annotation/geodia_baretti/RNAseq/work/conda/multiqc-c98eb6b85dda6e7c6d0116ad2fc6861c/lib/python3.9/site-packages/spectra/core.py", line 1, in <module>
      from colormath import color_objects, color_conversions                                                                                   File "/projects/annotation/geodia_baretti/RNAseq/work/conda/multiqc-c98eb6b85dda6e7c6d0116ad2fc6861c/lib/python3.9/site-packages/colormath/color_conversions.py", line 13, in <module>
      import networkx                                                                                                                          File "/projects/annotation/geodia_baretti/RNAseq/work/conda/multiqc-c98eb6b85dda6e7c6d0116ad2fc6861c/lib/python3.9/site-packages/networkx/__init__.py", line 114, in <module>
      import networkx.generators
    File "/projects/annotation/geodia_baretti/RNAseq/work/conda/multiqc-c98eb6b85dda6e7c6d0116ad2fc6861c/lib/python3.9/site-packages/networkx/generators/__init__.py", line 14, in <module>
      from networkx.generators.intersection import *
    File "/projects/annotation/geodia_baretti/RNAseq/work/conda/multiqc-c98eb6b85dda6e7c6d0116ad2fc6861c/lib/python3.9/site-packages/networkx/generators/intersection.py", line 13, in <module>
      from networkx.algorithms import bipartite
    File "/projects/annotation/geodia_baretti/RNAseq/work/conda/multiqc-c98eb6b85dda6e7c6d0116ad2fc6861c/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
      from networkx.algorithms.dag import *
    File "/projects/annotation/geodia_baretti/RNAseq/work/conda/multiqc-c98eb6b85dda6e7c6d0116ad2fc6861c/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
      from fractions import gcd
  ImportError: cannot import name 'gcd' from 'fractions' (/projects/annotation/geodia_baretti/RNAseq/work/conda/multiqc-c98eb6b85dda6e7c6d0116ad2fc6861c/lib/python3.9/fractions.py)

Work dir:
  /projects/annotation/geodia_baretti/RNAseq/work/38/0a84313fb783662f65c4e11cdd7f64

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Comment by mahesh-panchal** [comment]
Is /scratch visible inside a singularity container? Could you test it please?

**Comment by LucileSol** [comment]
no it is not

**Comment by mahesh-panchal** [comment]
Check if someone updated Singularity and didn't include scratch in the automounts. I think that has happened before.

**Comment by LucileSol** [comment]
Yes it solved the singularity problem!

**Comment by mahesh-panchal** [comment]
Re: MultiQC
Can you make a pull request and update it to the latest version please?

**Comment by LucileSol** [comment]
all fixed with new MultiQC version and Singularity fix
