### ISSUE TITLE
error with multiQC while running TranscriptAssembly.nf

### ISSUE THREAD

**Issue by LucileSol** [NBISweden/pipelines-nextflow#70]
I ran 
```
nextflow run -c params.config -profile nbis,conda ~/git/NBIS/pipelines-nextflow/TranscriptAssembly/TranscriptAssembly.nf
```
and got the following error :

```
Caused by:
  Process `transcript_assembly:multiqc` terminated with an error exit status (1)
 
Command executed:
 
  multiqc . -c multiqc_conf.yml
 
Command exit status:
  1
 
Command output:
  Searching   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 10/10  
 
Command error:
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/multiqc.py", line 594, in run
      output = mod()
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/modules/flash/flash.py", line 26, in __init__
      super(MultiqcModule, self).__init__(
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/modules/base_module.py", line 45, in __init__
      config.update({anchor: mod_cust_config.get("custom_config", {})})
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/utils/config.py", line 250, in update
      return update_dict(globals(), u)
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/utils/config.py", line 256, in update_dict
      if isinstance(val, collections.Mapping):
  AttributeError: module 'collections' has no attribute 'Mapping'
  ============================================================
 
 [ERROR  ]         multiqc : Oops! The 'seqyclean' MultiQC module broke... 
    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
    If possible, please include a log file that triggers the error - the last file found was:
      None
  ============================================================
  Module seqyclean raised an exception: Traceback (most recent call last):
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/multiqc.py", line 594, in run
      output = mod()
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/modules/seqyclean/seqyclean.py", line 18, in __init__
      super(MultiqcModule, self).__init__(
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/modules/base_module.py", line 45, in __init__
      config.update({anchor: mod_cust_config.get("custom_config", {})})
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/utils/config.py", line 250, in update
      return update_dict(globals(), u)
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/utils/config.py", line 256, in update_dict
      if isinstance(val, collections.Mapping):
  AttributeError: module 'collections' has no attribute 'Mapping'
  ============================================================
  [ERROR  ]         multiqc : Oops! The 'optitype' MultiQC module broke... 
    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
    If possible, please include a log file that triggers the error - the last file found was:
      None
  ============================================================
  Module optitype raised an exception: Traceback (most recent call last):
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/multiqc.py", line 594, in run
      output = mod()
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/modules/optitype/optitype.py", line 24, in __init__
      super(MultiqcModule, self).__init__(
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/modules/base_module.py", line 45, in __init__
      config.update({anchor: mod_cust_config.get("custom_config", {})})
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/utils/config.py", line 250, in update
      return update_dict(globals(), u)
    File "/projects/annotation/Lepidium_7/pacbio/hybrid_campestre_heterophyllum_LcxLh/RNAseq/work/conda/multiqc-3f02d6c39194cb687c5310d7a88b0ee5/lib/python3.10/site-packages/multiqc/utils/config.py", line 256, in update_dict
      if isinstance(val, collections.Mapping):
  AttributeError: module 'collections' has no attribute 'Mapping'
  ============================================================
  [WARNING]         multiqc : No analysis results found. Cleaning up..
  [INFO   ]         multiqc : MultiQC complete

```

the rest of the pipeline is running fine!

**Comment by LucileSol** [comment]
ah no actually The pipeline is not ending properly and stringtie does not run either...

**Comment by mahesh-panchal** [comment]
What's the stringtie error?
